// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RedLaserDemo
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int overlay_logo = 2130837505;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070007
			public const int btnScan = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int scan = 2131165193;
			
			// aapt resource value: 0x7f070000
			public const int scanOptionsLayout = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int textView1 = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int toggle128 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int toggle39 = 2131165190;
			
			// aapt resource value: 0x7f070002
			public const int toggleEAN = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int toggleQR = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int toggleUPC = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int udidString = 2131165192;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int main = 2131099648;
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int beep = 2130968576;
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int barcodeTypes = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int scan = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int scan128Barcodes = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int scan39Barcodes = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int scanEAN8Barcodes = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int scanQRBarcodes = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int scanUPCBarcodes = 2131034117;
			
			private String()
			{
			}
		}
	}
}
